# Generated by Django 3.2.3 on 2021-06-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0003_auto_20210615_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zsedata',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
